### ISSUE TITLE
We appear to be copying a TEI element to the RNG output

### ISSUE THREAD

**Issue by martindholmes** [TEIC/atop#27]
This template from the transpile.xslt:

~~~~~
  <xsl:template match="moduleRef[@url]/content" as="element(content)">
    <xsl:variable name="vInclusion" as="node()">
      <xsl:apply-templates mode="atop:rngCombine" select="doc(../@url)"/>
    </xsl:variable>
    <xsl:copy>
      <xsl:sequence select="@*"/>
      <xsl:apply-templates select="$vInclusion">
        <xsl:with-param name="tpPrefix" as="xs:string" select="../@prefix"/>
      </xsl:apply-templates>
      <xsl:apply-templates select="node()"/>
    </xsl:copy>
  </xsl:template>
~~~~~

appears to copy the TEI content element which is a child of moduleRef to the RNG output. @HelenaSabel and I don't quite understand what's happening here. We need to determine if this is what's happening, and if so, what should happen instead; and we should have more tests for checking moduleRef handling at the transpile stage.

**Comment by sydb** [comment]
The only child of `<moduleRef>` is `<content>`, which is used to specify RELAX NG code that is _also_ used in the output schema, in addition to the RELAX NG found in the `<content>` at the end of `@url`, if any. This template matches that `<content>`, and copies over both chunks of RELAX NG.

I suppose there is a worry that the `<content>` has not RELAX NG, but rather TEI descendants. (There are no extant cases of this in the entire atop/ or TEI/P5/ directories, but it _could_ happen.)

We should either
1. Leave code as is, add constraint to ploddSchemaSpecification.odd to limit this `<content>` to only RELAX NG children.
2. Change code to check for `<tei:*>`, not copy it, and issue a warning instead.
3. Leave code as is, if user puts `<tei:*>` in a `<content>` in a `<moduleRef>` the output schema will be broken without warning.

I like (1) the most and hate (3). I like (1) so much better, I just thought “why didn’t we already do that?” to myself and then checked. I discovered two things.

1. There _is no_ ploddSchemaSpecification.odd in our "main" branch.
2. The ploddSchemaSpecification.odd schema (which is, appropriately, in "dev" branch) _does_ have a constraint that limits the content of `/tei:moduleRef/tei:content` to RELAX NG (either `<rng:*>` or `<a:*>`).

**Comment by sydb** [comment]
HOWEVER, that constraint ("only_rng_in_moduleRef_content") does _not_ have an `<sch:rule>`, which it now needs. Probably true of other constraint specifications in that schema …

**Comment by martindholmes** [comment]
Issue is not an issue, and tangential fix applied.
