### ISSUE TITLE
Add XInclude flag to all invocations of XSLT (and make them consistent how they call XSLT)

### ISSUE THREAD

**Issue by martindholmes** [TEIC/atop#42]
Per meeting with @sydb and @HelenaSabel on 2024-10-16, we agreed that we should always use the XInclude flag whenever Saxon runs, because we can not come up with any reason not to process any XInclude when first encountered.

**Comment by martindholmes** [comment]
In progress in branch issue-42-xinclude.

**Comment by sydb** [comment]
Done!
