### ISSUE TITLE
Clarify how to obtain a QName from an attDef

### ISSUE THREAD

**Issue by dmj** [TEIC/atop#7]
The ```<attDef>``` contains the definition of a single attribute. An XML attribute has a name which is a QName consisting of a possibly empty namespace URI, an optional prefix and a local name. The QName of a specified attribute is obtained as followed:

1. The namespace URI is the empty string unless specified otherwise in the @ns attribute.
2. The local name is specified by the ```@ident``` attribute unless specified otherwise in the first ```<altIdent>``` child element.

The QName of a specified attribute thus can be constructed as follows:

```QName( (@ns, "")[1], (tei:altIdent[1], @ident)[1])```

**Comment by dmj** [comment]
See #6

**Comment by martindholmes** [comment]
@HelenaSabel, @sydb and I believe the current implementation is correct.
